### ISSUE TITLE
Can't use the MongoDB URL format for connection

### ISSUE THREAD

**Issue by riggerthegeek** [db-migrate/mongodb#14]
It seems I can't use the modern URL format for connecting (eg, 'mongodb://host:port/database') - when I do, it tells me I need to specify the database parameter.

Would anyone object if I did a PR that allowed for both the existing object and the URL based connection string?

**Comment by wzrdtales** [comment]
@riggerthegeek Actually this is working, just tried to reproduced but everything just works as expected.

Can you please give more information about your environment?

- node version
- npm version
- db-migrate version
- db-migrate-mongodb version
- os
- a sample config you used

Thank you

**Comment by riggerthegeek** [comment]
Strange

Versions:
Node: 6.9.4
npm: 3.10.10
db-migrate: 0.10.0-beta.20
db-mongodb: 1.2.0
OS: Ubuntu I think - it's the official Docker image

My `database.json` is:

```
{
  "mongodb": {
    "driver": "mongodb",
    "url": {
      "ENV": "MY_MONGODB_URL"
    }
  }
}
```
The env is set in the Docker container and can confirm it's correct. I still get the same error if I use:

```
{
  "mongodb": {
    "driver": "mongodb",
    "url": "mongodb://localhost:27017/dbname"
  }
}

Am I using it different to you?

**Comment by wzrdtales** [comment]
@riggerthegeek Yes you have a wrong config.

This:

```json
{
  "mongodb": {
    "driver": "mongodb",
    "url": {
      "ENV": "MY_MONGODB_URL"
    }
  }
}
```

would turn into this:

```json
{
  "mongodb": {
      "ENV": "MY_MONGODB_URL"
  }
}
```

But don't bother to do this, it is even easier than the above.

Just use DATABASE_URL as environment variable instead and you won't even need a database.json! :)

**Comment by riggerthegeek** [comment]
Yup, that works perfectly. Thanks.
