### ISSUE TITLE
Driver doesn't close connection

### ISSUE THREAD

**Issue by raffaele-clevermind** [db-migrate/mongodb#32]
the method close for the mondo driver does nothing other then return a successfull promise, which means that the migration process doesn't close the connection

```javascript
   /**
   * Closes the connection to mongodb
   */
   close: function(callback) {
     return Promise.resolve().nodeify(callback);
   }
```

**Comment by wzrdtales** [comment]
No that is wrong. The mongodb driver currently has no active connection it utilizes, but an on demand connection spawned. So closed can't do anything, so this is correct.

See https://github.com/db-migrate/mongodb/blob/1ff05098dc777434b36de3b603f716cf55647c8b/index.js#L270
