### ISSUE TITLE
The driver you are using does not support the new state management.

### ISSUE THREAD

**Issue by djw-sl** [db-migrate/mongodb#48]
I get this warning and **no migrations run** when calling `db-migrate up`

Here is my setup:

`db-migrate` version: 1.0.0-beta15
`db-migrate-mongodb` version: 1.5.0

in my migrations folder I have setup a `package.json` file with the following:

```json
{
  "type": "module"
}
```

so that I can use ESM and imports in my migrations.

**Comment by wzrdtales** [comment]
this is not a bug, just a warning. the mongodb driver is indeed missing the new state management, however, if you don't use v2 migrations (which is unlikely since they're intentionally not yet documented) there is nothing to worry about.

**Comment by djw-sl** [comment]
Ok thanks.

Would there be any reasons of why my new migration file is not picked up?

When I create a new migration and the run `db-migrate up` I only get the following info:

```
$ db-migrate up
[WARN] The driver you are using does not support the new state management. Please raise an issue in the repository of your driver maintainer
[INFO] [migration] Nothing to run
[INFO] Done
```

The new migration file is not ran.
